backend = "glx";

vsync = true;

animations = ({
    triggers = [ "open", "show" ];
    preset = "appear";
}, {
    triggers = [ "close", "hind" ];
    preset = "disappear";
}, {
    triggers = [ "geometry" ];
    preset = "geometry-change";
})

rules = (
    {
        match = "class_i = 'fcitx'";
        animations = ({
            # -- https://picom.app
            # If animation scripts are defined in multiple matching
            # rules, they will be merged together. If multiple
            # matching rules contain animation scripts for the same
            # trigger, the last one will take effect, the same as
            # other options.
            # --
            triggers = [ "open", "show", "close", "hind", "geometry"];
        });
    }
)
