backend = "xrender";

animations = ({
	triggers = [ "open", "show" ];
	preset = "appear";
}, {
	triggers = [ "close", "hide" ];
	preset = "disappear";
})

vsync = true;

# inactive-opacity = 0.9;
# opacity-rule = [
#     "85:class_g = 'Alacritty'",
#     "100:class_g = 'Dmenu'"
# ];
# 
# blur: 
# {
#     method = "dual_kawase";
#     size = 10;
#     deviation = 5.0;
# };
# blur-background-exclude = [
#     "window_type = 'dock'",
#     "window_type = 'desktop'",
#     "name ~= 'overlay'"
# ];

