[general]
import = [
  "~/.config/alacritty/gruvbox_dark.toml"
]

[window]
# handled by picom
#opacity = 0.8
padding = { x = 0, y = 0 }

[font]
#normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
normal = { family = "Iosevka", style = "Regular" }
size = 10.0
