theme = "gruvbox"

[editor]
true-color = true
color-modes = true
line-number = "relative"
cursorline = true
indent-guides.render = true
bufferline = "multiple"
mouse = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[keys.normal]
"C-r" = ":reload"

[keys.insert]
"j" = { k = "normal_mode" }
